[project]
name = "vector-db-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Usman Ihsan", email = "usmanihsann@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "chromadb>=1.5.9",
    "numpy>=2.5.2",
    "ollama>=0.6.2",
    "openai>=2.53.0",
    "python-dotenv>=1.2.2",
]

[project.scripts]
vector-db-course = "vector_db_course:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[tool.uv.workspace]
members = [
    "src/chroma-db",
]
